version: '3'
services:
  # PHPアプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zenflow_app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - zenflow

  # Webサーバー
  nginx:
    image: nginx:1.25-alpine
    container_name: zenflow_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - zenflow

  # データベース
  db:
    image: mysql:8.0
    container_name: zenflow_db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: zenflow
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: zenflow
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - zenflow

  #phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: zenflow_phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - zenflow

networks:
  zenflow:
    driver: bridge

volumes:
  dbdata: